name: Build and Release WPF App

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

permissions:
  contents: write  # Required to create releases and upload assets
  id-token: write  # Required for authentication (if needed)

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  # Adjust to your .NET version

      - name: Restore dependencies
        run: dotnet restore quizer-desktop.sln

      - name: Build the project
        run: dotnet build quizer-desktop.sln --configuration Release

      - name: Publish the project
        run: dotnet publish quizer-desktop.sln --configuration Release --output ./output --self-contained --publish-single-file

      - name: List output files
        run: dir D:\a\quizer-desktop\quizer-desktop\quizer-desktop\bin\Release\net8.0-windows


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.run_id }}  # Use the run ID as the tag name for uniqueness
          release_name: Manual Release # Release name, can customize
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .exe to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/quizer-desktop.exe  # Path to the generated executable
          asset_name: quizer-desktop.exe  # Name for the asset in the release
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
